name: Find VM 2026 ID

on:
  workflow_dispatch:

jobs:
  hent-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installer Python dependencies
        run: pip install requests imapclient

      - name: Find VM 2026 ID
        run: |
          python3 << 'PYEOF'
          import requests
          import os

          headers = {
              'x-apisports-key': os.environ['API_FOOTBALL_TOKEN']
          }

          r = requests.get('https://v3.football.api-sports.io/leagues?name=FIFA World Cup', headers=headers)
          print(r.json())
          PYEOF
        env:
          API_FOOTBALL_TOKEN: ${{ secrets.API_FOOTBALL_TOKEN }}

      - name: Commit og push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git diff --staged --quiet || git commit -m "Opdater data.json"
          git push
