- name: Find VM 2026 ID
        run: |
          python3 << 'EOF'
          import requests
          import os

          headers = {
              'x-apisports-key': os.environ['API_FOOTBALL_TOKEN']
          }

          r = requests.get('https://v3.football.api-sports.io/leagues?name=FIFA World Cup', headers=headers)
          print(r.json())
          EOF
        env:
          API_FOOTBALL_TOKEN: ${{ secrets.API_FOOTBALL_TOKEN }}
